### ISSUE TITLE
Josh\Component\PhantomJs\Facade\PhantomJs not found

### ISSUE THREAD

**Issue by feralheart** [mrjosh/laravel-phantomjs#1]
I got this exception after install.

**Comment by mrjosh** [comment]
Hi, Thanks for the issue. make sure you have ```josh/laravel-phantomjs``` package version ```1.0.1``` on your vendor directory by pathing ```./vendor/josh/laravel-phantomjs/```

you can see the builds here ``` https://travis-ci.org/iamalirezaj/laravel-phantomjs ``` are passed so everything is okay , you must check your install location to sure you have the package .

Regards, Josh
