### ISSUE TITLE
laravel 6.2 unable to install

### ISSUE THREAD

**Issue by p2p-sys** [mrjosh/laravel-phantomjs#10]
- josh/laravel-phantomjs 1.1 requires laravel/framework ^5 -> satisfiable by laravel/framework[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.1.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.2.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.3.x-dev, v6.2.0].
    - Can only install one of: laravel/framework[5.4.x-dev, v6.2.0].
    - Installation request for laravel/framework (locked at v6.2.0, required as ^6.2) -> satisfiable by laravel/framework[v6.2.0].

**Comment by Christoph-Harms** [comment]
Same here for Laravel 6.4

**Comment by mrjosh** [comment]
Sorry for this late message. 
The problem fixed in [1.1.6](https://github.com/MrJoshLab/laravel-phantomjs/releases/tag/1.1.6) version now.

You can now install the latest version with:

```shell
composer require josh/laravel-phantomjs:1.1.6
```

Regards.
