### ISSUE TITLE
Delay function?

### ISSUE THREAD

**Issue by metallurgical** [mrjosh/laravel-phantomjs#13]
May i know, is there a delay function which the same to this [Delay Page Render](http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/#delay-page-render)?

**Comment by mrjosh** [comment]
Hey, I hope you doing well.

Yeah, The ```\PhantomJs::request``` method is actually a shortcut for ```$client->getMessageFactory()->createRequest('http://jonnyw.me')``` 

It returns ```JonnyW\PhantomJs\Http\Request``` object. 

You can do something like this

```php
$request = \PhantomJs::get('https://www.google.com/').setDelay(1000);
$response = \PhantomJs::send($request);

if($response->getStatus() === 200) {

    // Dump the requested page content
    var_dump($response->getContent());
}
```

If you want to access to methods like ```createRequest``` or ```createCaptureRequest``` you can have them with ```getClient``` method.

you can get client like:
```php
$client = \PhantomJs::getClient();

$request = $client->getMessageFactory()->createCaptureRequest('http://jonnyw.me');
$request->setDelay($delay);
```

or maybe if you had custom client instance you can set it like:
```php
\PhantomJs::setClient($client);
```

I hope this will help you. Good luck. 👍

**Comment by metallurgical** [comment]
Thanks for pointing it out man. Thanks again
