### ISSUE TITLE
fresh install not ok 

### ISSUE THREAD

**Issue by khyoz** [mrjosh/laravel-phantomjs#3]
php 7.1.7 windows 10 laravel 5.6
ErrorException (E_WARNING)
Declaration of JonnyW\PhantomJs\DependencyInjection\ServiceContainer::load() should be compatible with Symfony\Component\DependencyInjection\Container::load($file)

**Comment by mrjosh** [comment]
https://github.com/iamalirezaj/laravel-phantomjs/commit/ec9a817b0b8ac4fdd7cc0ce18a04d8ccc61204af There was many issues from symfony v3. updated dependency repo from symfony v3 to v4 and fixed.

You can install the latest version of package with version 1.0.2
```bash
composer require josh/laravel-phantomjs:1.0.2
```

Thanks for issue and good luck.
