### ISSUE TITLE
Wait while all page resources loaded

### ISSUE THREAD

**Issue by romansidorov** [mrjosh/laravel-phantomjs#5]
Hello,

is there any method that allows to set waiting while all page resources loaded before start to render?

Thanks.

**Comment by mrjosh** [comment]
Hey there,

I just added isLazy method in PhntomJs Helper client and tagged in https://github.com/iamalirezaj/laravel-phantomjs/releases/tag/1.1.1

According to http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/ You can use isLazy method in client object which is 
```php
\PhantomJs::isLazy()->send($request);
// Tells the client to wait for all resources before rendering
```

You can update the package to 1.1.1 and use this feature or if you wanna use more features of phantomjs client from here => http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/
you can use below configuration.
```php
// get main client
$client = \PhantomJs::getClient();

// Use options of client you can find here http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/

// then set the options to Helper PhantomJs object
\PhantomJs::setClient($client);
```

i hope you're doing well and thanks for the issue.
-Josh

**Comment by romansidorov** [comment]
Thanks a lot! 👍
